"""8 commit

Revision ID: 1b83c596e564
Revises: b37659f4793a
Create Date: 2024-10-17 00:24:42.048762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b83c596e564'
down_revision: Union[str, None] = 'b37659f4793a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coefficient', sa.Column('now_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coefficient', 'now_datetime')
    # ### end Alembic commands ###
